### ISSUE TITLE
Dump dict to json instead of adding new line

### ISSUE THREAD

**Issue by cdw** [AllenCellModeling/sarcomereannotation#8]
https://github.com/AllenCellModeling/lineannotation/blob/21682d68fe15779466b3b9bb7edc83f582b892c9/lineannotation/SarcomereLines.py#L89

The way that the file is saved currently means you'll error when you try to read it in as a json file (`JSONDecodeError: Extra data: line 2 column 1 (char 17)`) because you have two root elements. 

If you swap to saving a dict like:
```
with open(fname, "w") as fp:
            json.dump(img_size, fp)
            fp.write("\n")
            json.dump(self.lines, fp)
```
becomes
```
with open(fname, "w") as fp:
            json.dump({'size':img_size, 'lines':self.lines}, fp)
```
then the json file should be valid.

**Comment by heeler** [comment]
I was thinking of this as more of a header but making it part of the json object makes more sense.
